function [resultData,resultName, titleNames, german_titles] = load_Dalk(idx)
% function that contains all names that are relevant to the Dalkmann
% datasets

% If idx does not exist, create it as a vector that covers all datasets
if ~exist("idx","var")
  idx = 1:13;
end

% Name of the datasets
resultData = ["data_BEZ_ns_Dalk", "data_BEZ_s_Dalk",...     1:2
              "data_CAR_ns_Dalk", "data_CAR_s_Dalk_mod",... 3:4
              "data_CIP_ns_Dalk",...                        5
              "data_DIC_ns_Dalk", "data_DIC_s_Dalk",...     6:7
              "data_NAP_ns_Dalk", "data_NAP_s_Dalk",...     8:9
              "data_SMX_ns_Dalk", "data_SMX_s_Dalk",...     10:11
              "data_TRI_ns_dalk", "data_TRI_s_dalk"];       %12:13
resultData = resultData(idx);

%Names for file names and similar
resultName = ["BEZ_ns_Dalk", "BEZ_s_Dalk",...
              "CAR_ns_Dalk", "CAR_s_Dalk",...
              "CIP_ns_Dalk",...
              "DIC_ns_Dalk", "DIC_s_Dalk",...
              "NAP_ns_Dalk", "NAP_s_Dalk",...
              "SMX_ns_Dalk", "SMX_s_Dalk",...
              "TRI_ns_dalk", "TRI_s_dalk"];
resultName = resultName(idx);

% Names for plot titles
titleNames = ["Bezafibrate non-sterile", "Bezafibrate sterile",...
              "Carbamazepine non-sterile", "Carbamazepine sterile",...
              "Ciprofloxacin non-sterile",...
              "Diclofenac non-sterile", "Diclofenac sterile",...
              "Naproxen non-sterile", "Naproxen sterile",...
              "Sulfamethoxazole non-sterile", "Sulfamethoxazole sterile",...
              "Trimethoprim non-sterile", "Trimethoprim sterile"];
titleNames = titleNames(idx);

% German names for plot titles
german_titles = ["Bezafibrat nicht-steril", "Bezafibrat steril",...
              "Carbamazepin nicht-steril", "Carbamazepin steril",...
              "Ciprofloxacin nicht-steril",...
              "Diclofenac nicht-steril", "Diclofenac steril",...
              "Naproxen nicht-steril", "Naproxen steril",...
              "Sulfamethoxazol nicht-steril", "Sulfamethoxazol steril",...
              "Trimethoprim nicht-steril", "Trimethoprim steril"];
german_titles = german_titles(idx);
end